CXX             = g++
CXXFLAGS        = -c
OPTFLAG         = 
DEBUGFLAG       =
LINKER          = g++


SRC = \
    passwd.cpp \
    ls.cpp 

passwd:
	g++ passwd.cpp -o passwd

ls: 
	g++ ls.cpp -o ls

all:
	ls passwd

clean:
	rm ls passwd
