#!/bin/bash

genos="Linux"
hostname="salmonlinux"
timestamp="Mon 1 June 10:52:32 PDT 2013"
kernel="4.8.1-1337"
arch="x86_64"
kernver="SMP PREEMPT $timestamp"
proc="Intel(R) i13 CPU 1750K @ 7.1 GHz"
hardware="GenuineIntel"
osfam="GNU + Linux"
unamever="uname (GNU coreutils) 19.20
Packaged by Salmon Linux (8.20 (p1.0))
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
"
halp="Usage: uname [OPTION]...
Print certain system information.  With no OPTION, same as -s.

  -a, print all information, in the following order,
  -s, print the kernel name
  -n, print the network node hostname
  -r, print the kernel release
  -v, print the kernel version
  -m, print the machine hardware name
  -p, print the processor type or "unknown"
  -i, print the hardware platform or "unknown"
  -o, print the operating system
  --help     display this help and exit
  --version  output version information and exit

   Report uname bugs to bug-coreutils@gnu.org
   GNU coreutils home page: <http://www.gnu.org/software/coreutils/>
   General help using GNU software: <http://www.gnu.org/gethelp/>
   For complete documentation, run: info coreutils 'uname invocation'
"

if [[ $1 == "" ]]; then
	echo "$genos"
fi

case "$1" in
	-a) echo "$osfam $hostname $kernel $kernvar $arch $osfam"
		;;
	-m) echo "$arch"
		;;
	-n) echo "$hostname"
		;;
	-r) echo "$kernel"
		;;
	-v) echo "$kernver"
		;;
	-p) echo "$proc"
		;;
	-i) echo "$hardware"
		;;
	-o) echo "$osfam"
		;;
	--version) echo "$unamever"
		;;
	--help) echo "$halp"
esac
