.SH "NAME"
.P
spawn \- fry manager utility

.SH "SYNOPSIS"
.P
.B
spawn
fry

.SH DESCRIPTION
.P
.B
spawn
is the primary packaging tool for Salmon Linux.

.SH OPTIONS
.P
.B
spawn
has no options, you simply provide the name of the fry you wish to install.

.SH EXAMPLES
.P
.B
spawn
perl
.RS
spawns the perl
.I
fry
.RE

.SH BUGS
.P
Currently,
.B
spawn
does not support the installation of more than one fry at a time. This will
hopefully be corrected in later releases.

.SH SEE ALSO

.SH HISTORY
.P
2013 - written by Marcus Hildum
