#!/bin/bash
rand=`tr -dc [:alnum:] < /dev/urandom | head -c 39` 
echo -e "$1: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0xb$rand, stripped"

